name: '[Workflow] Sync Template Files to Application Repos'

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
      - '.vscode/**'
      - '.dockerignore'
      - '.editorconfig'
      - '.env.example'
      - '.gitignore'
      - '.releaserc'
      - 'AGENTS.md'
      - 'Makefile'
  workflow_dispatch:
    inputs:
      topic:
        description: 'GitHub topic to filter repositories (default: application)'
        required: false
        default: 'application'
      dry_run:
        description: 'Perform a dry run without making changes'
        required: false
        default: false
        type: boolean

jobs:
  sync-files:
    name: 'Sync Template Files'
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4

      - name: Mint GitHub App installation token (owner-based)
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WEBGRIP_CI_CLIENT_ID }}
          private-key: ${{ secrets.WEBGRIP_CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Sync files
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          branches: "^main$"
          github_token: ${{ steps.app-token.outputs.token }}
          patterns_to_ignore: >
            .github/workflows/on_synced_files_change.yml,
            .github/workflows/copilot-setup-steps.yml
          patterns_to_include: >
            .github/workflows,
            .vscode,
            .dockerignore,
            .editorconfig,
            .env.example,
            .gitignore,
            .releaserc,
            AGENTS.md,
            Makefile
          topics_to_include: "${{ github.event.inputs.topic || 'application' }}"
          exclude_private: false
          exclude_forked: false
          committer_username: "webgrip-bot"
          committer_email: "bot@webgrip.nl"
          commit_message: "ci: update from upstream ${{ github.repository.name }}@${{ github.sha }}"
          bot_branch_name: "ci/sync-template-${{ github.sha }}"
          # patterns_to_remove: ".github/workflows/sync-template-files.yml"


  # sync-files:
  #   name: 'Sync Template Files'
  #   uses: webgrip/workflows/.github/workflows/sync-template-files.yml@main
  #   with:
  #     topic: ${{ github.event.inputs.topic || 'application' }}
  #     dry-run: ${{ github.event.inputs.dry_run || 'false' }}
  #     paths: >
  #       .editorconfig,
  #       .dockerignore,
  #       .env.example,
  #       AGENTS.md,
  #       Makefile,
  #       .gitignore,
  #       .releaserc.json,
  #       .vscode/**,
  #       docs/techdocs/**,
